-- Generated by nwg-displays on 2026-08-01 at 00:44:50. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@144.0",
    position = "1920x0",
    scale = 1.7000000000000002
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@144.0",
    position = "0x173",
    scale = 1.0
})
